#!/usr/bin/env python3

import os, sys

def step(x : int) -> int:
    if x <= 0:
        return 0
    if 0 < x <= 20:
        return 20
    if 20 < x <= 100:
        return x

    return 100

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: brightness <level>", file=sys.stderr)
        sys.exit(1)

    brightness = sys.argv[1]
    brightness = brightness.replace("%", "")
    if not brightness.isdigit() or int(brightness) < 0 or int(brightness) > 100:
        print("Brightness must be a number between 0 and 100", file=sys.stderr)
        sys.exit(1)

    brightness = step(int(brightness))

    with open("/sys/class/backlight/backlight/brightness", "w") as f:
        f.write(str(brightness))