#!/bin/sh

set -e

# ver 1.1.46
FW_URL="https://download.chitubox.com/chitusystems/chitusystems/public/printer/firmware/release/1/ca8e1d9a20974a5896f8f744e780a8a7/1/01.01.46/2025-10-22/f9bd2b9b1926408ca238de8e7eac69b6.bin"
DECRYPT="/usr/bin/swu-decrypt.py"
KEY="78B6A614B6B6E361DC84D705B7FDDA33C967DDF2970A689F8156F78EFE0B1FCE"
IV="54E37626B9A699403064111F77858049"
BINFILE="/user-resource/update.bin"
SWUFILE="/user-resource/update.swu"

SERIALPORT_BED="/dev/ttyS4"
STOCK_FW_BED="/lib/firmware/katapult-deployer-stock-bed.bin"

SERIALPORT_TOOLHEAD="/dev/ttyAMA0"
STOCK_FW_TOOLHEAD="/lib/firmware/katapult-deployer-stock-toolhead.bin"

# Download firmware
curl -k -o "$BINFILE" -L "$FW_URL"

# Decrypt firmware
exec "$DECRYPT" "$BINFILE" "$KEY" "$IV" "$SWUFILE"

# Install firmware
flash "$SWUFILE"

# Flash stock bootloader
service klipper stop
flashtool -d $SERIALPORT_BED -b 115200 -r
flashtool -d $SERIALPORT_BED -f $STOCK_FW_BED -b 115200
flashtool -d $SERIALPORT_TOOLHEAD -f $STOCK_FW_TOOLHEAD

# Clean up firmware files
rm "$BINFILE" "$SWUFILE"

reboot
