#!/bin/sh

set -e

FW_URL="https://github.com/OpenCentauri/yocto-opencentauri/releases/latest/download/update.swu"
SWUFILE="/user-resource/update.swu"

# Download firmware
curl -k -o "$SWUFILE" -L "$FW_URL"

# Install firmware
flash "$SWUFILE"

# Clean up firmware file
rm "$SWUFILE"

reboot
