#!/bin/sh

if [ ! -f "$1" ]; then
    echo "Usage: $0 path/to/update.swu"
    exit 1
fi

case "$1" in
    *.swu) ;;
    *)
        echo "Error: file must be an .swu file"
        exit 1
        ;;
esac

curr=$(fw_printenv boot_partition | awk -F= '{ print $2 }' | tr -d '[:space:]')

if [ "$curr" = "bootA" ]; then
    boot_partition="now_A_next_B"
elif [ "$curr" = "bootB" ]; then
    boot_partition="now_B_next_A"
else
    exit 1
fi

echo "$boot_partition"

set -e

sync
swupdate -i "$1" -e "stable,${boot_partition}"
sync
echo "Update finished, run 'reboot' to finalize"
